### ISSUE TITLE
Adding es6 type to riotPreprocessor causes error. 

### ISSUE THREAD

**Issue by StephenTurley** [riot/karma-riot#16]
adding the following to my karma config causes error:

```
riotPreprocessor: {
      options: {
        type: 'es6'
      }
    },

```

```
[TypeError: Cannot read property 'first_line' of undefined]
TypeError: Cannot read property 'first_line' of undefined
```

See an example here:
https://github.com/StephenTurley/hello-riot/tree/riot-bug

**Comment by cognitom** [comment]
I think `babel` is supposed to be included as a dependency.

**Comment by GianlucaGuarini** [comment]
@StephenTurley please check our official doc http://riotjs.com/guide/compiler/#ecmascript-6

**Comment by StephenTurley** [comment]
So the preprocessor requires global dependencies?

**Comment by cognitom** [comment]
You don't have to install `babel` globally. Just install it locally by yourself. `--save-dev` is enough:

``` bash
$ npm install --save-dev babel-preset-es2015-riot babel-core
```

**Comment by StephenTurley** [comment]
👍
