### ISSUE TITLE
Keys and values are different in real browsers to karma browsers

### ISSUE THREAD

**Issue by samhstn** [riot/karma-riot#19]
At the moment I cannot identify if the issue is with karma or with riot, but I hope you can help me with this issue.

Also, I am not really sure if I have followed best practices for demonstrating the bug.

I have demonstrated the bug in a repository I made here: https://github.com/shouston3/riot-bug

#### Description:

When mapping over an object using riot's `each` helper method, the object keys and values switch depending on if you run it in browser or if you run the karma tests

#### Steps to replicate

Clone the repository
```
git clone https://github.com/shouston3/riot-bug && cd riot-bug
```

Install the dependencies
```
npm install
```

Start the server
```
npm start
```

Visit: `http://localhost:8080` and you should see:
```
obj - [object Object]
```

Now run the tests:
```
npm test
```

The object keys of `this.content` should have switched around

And you should see the `innerHTML` of the div will be:

```
[object Object] - obj
```

Let me know if this is expected or if it is some sort of bug

**Comment by cognitom** [comment]
Hi @shouston3.
It seems that you're using different version in browser(2.6.7) and testing(3.0.1).

- karma-riot@1.* supports riot@2.*
- karma-riot@2.* supports riot@3.*

**Comment by cognitom** [comment]
@shouston3 we made breaking change on `each`. Check this issue, too.
http://riotjs.com/release-notes/#november-22-2016
https://github.com/riot/riot/issues/1420

And also our migration guide here:
http://riotjs.com/guide/migration-from-riot2/#object-loops

Riot 2.*:

```html
<div each={obj_key, obj in content}>
  {obj_key} - {obj}
</div>
```

Riot 3.*:

```html
<div each={obj, obj_key in content}>
  {obj_key} - {obj}
</div>
```
