### ISSUE TITLE
ignoring require statements

### ISSUE THREAD

**Issue by syropian** [riot/karma-riot#5]
I'm requiring [RiotControl](https://github.com/jimsparkman/RiotControl) in my `.tag` file, as I'm using Browserify to bundle my js. Tests seem to choke though saying `Can't find variable: require`. Any way force tests to ignore that? I'm adding the require statement at the very top of the `.tag` file.

**Comment by cognitom** [comment]
@syropian have you tried [karma-commonjs](https://github.com/karma-runner/karma-commonjs)? It could help you, I think.

**Comment by dp-lewis** [comment]
I've had some success with using Riotify.

Using something like this in my `karma.conf.js` file:

```
frameworks: ['browserify', 'jasmine'],
```

```
preprocessors: {
  'tags/**/*.tag': ['browserify'],
  'test/**/*Spec.js': ['browserify']
},
```

```
browserify: {
  debug: true,
  transform: [ 'riotify' ]
}
```

**Comment by cognitom** [comment]
@dp-lewis nice idea!
That seems straightforward.

**Comment by syropian** [comment]
@dp-lewis Nice! Did you have to install `karma-browserify` for that to work?

I ended up just running the tests against the final bundled js and that works pretty well too.

**Comment by dp-lewis** [comment]
@syropian I ended up doing the same thing for a bit :)

Here's a stripped down version of the set up I'm now using: https://github.com/dp-lewis/riot-testing-browserify

Running on Travis with Firefox is also included :)

In my example earlier I included the `.tag` files in  the karma.conf.js file, that's not needed.

**Comment by syropian** [comment]
@dp-lewis Thanks, this is great!
