### ISSUE TITLE
riotPreprocessor options for es6

### ISSUE THREAD

**Issue by stephanfriedrich** [riot/karma-riot#8]
Hi,
im noob with riotjs, but i try to deal with it. 
i use riotjs, babel, and webpack in a new test-environment to create web-apps.

i try to write tests for my custom-elements with karma, mocha and chai, and everything works fine.
but if i use `script type="text/es6"` within my custom-elements i got an error from karma.

to fix this i have to tell riot to precompile with type=> es6. 

**i dont know were to specify these option.**
can you help my?

**Comment by StarpTech** [comment]
I also run into the same issue.

**Comment by GianlucaGuarini** [comment]
Our whole test suite workis with karma + `rollup` using `es6` code transpiled via [rollup-plugins](https://github.com/riot/riot/blob/2000b3804995339481f13bf4adb4945dac5e63e5/test/karma.conf.js#L60-L72) thanks to [buble](https://www.npmjs.com/package/buble)

The documentation regarding the `es6` setup is really clear [karma options](https://github.com/riot/karma-riot#options) + [riot-compiler setup](http://riotjs.com/guide/compiler/#ecmascript-6)

Could you tell me more precisely what doesn't work? Have you followed all the steps?

**Comment by StarpTech** [comment]
You also use `karma-riot`? I will prepare a repository to reproduce the error. But it would be also great to cover this case in the test suite of this repo.

**Comment by StarpTech** [comment]
@stephanfriedrich I could fix it you have to follow the [es6 instructions](http://riotjs.com/guide/compiler/#pre-compilation) and install all dependencies as well as add `riotPreprocessor` to the karma config (http://riotjs.com/guide/compiler/#pre-compilation) on the Riot homepage. We could add an example how to configure it with es6 @GianlucaGuarini ?

```js
// karma.conf.js
module.exports = function (config) {
  config.set({
    frameworks: ['mocha', 'riot'],
    plugins: [
      'karma-mocha',
      'karma-mocha-reporter',
      'karma-phantomjs-launcher',
      'karma-riot'
    ],
    files: [
      '**/*.tag',
      'test/**/*.js',
      'node_modules/expect.js/index.js'
    ],
    preprocessors: {
      '**/*.tag': ['riot']
    },
    riotPreprocessor: {
      options: {
        type: 'es6'
      }
    },
    browsers: ['PhantomJS'],
    reporters: ['mocha']
  })
}
```

Install

```
  "devDependencies": {
    "babel-core": "^6.25.0",
    "babel-preset-es2015-riot": "^1.1.0",
    "expect.js": "^0.3.1",
    "karma": "^1.7.0",
    "karma-mocha": "^1.3.0",
    "karma-mocha-reporter": "^2.2.3",
    "karma-phantomjs-launcher": "^1.0.4",
    "karma-riot": "^2.0.0",
    "mocha": "^3.4.2",
    "phantomjs-prebuilt": "^2.1.14",
    "riot": "^3.6.1"
  }
```
.babelrc
```
{
  "presets": [
    "es2015-riot"
  ]
}
```

**Comment by StarpTech** [comment]
I could reproduce another issue

This works 
```
<hello>
  <h1>{ message }</h1>
  <script>
    class A {}
    var a = () => {}
    var [a, , b] = [1,2,3]
    this.message = 'Hello!'
  </script>
</hello>
```
but this fails
```
<hello>
  <h1>{ message }</h1>
  <script>
    test() {
    }
    this.message = 'Hello!'
  </script>
</hello>
```

Error
```
14 07 2017 17:02:27.767:ERROR [karma]: TypeError: Cannot read property 'first_line' of undefined
    at E:\Repositorys\riot-rollup-example\node_modules\karma-riot\index.js:28:75
    at nextPreprocessor (E:\Repositorys\riot-rollup-example\node_modules\karma\lib\preprocessor.js:36:26)
    at E:\Repositorys\riot-rollup-example\node_modules\karma\lib\preprocessor.js:122:9
    at module.exports (E:\Repositorys\riot-rollup-example\node_modules\isbinaryfile\index.js:28:12)
    at E:\Repositorys\riot-rollup-example\node_modules\karma\lib\preprocessor.js:84:7
    at E:\Repositorys\riot-rollup-example\node_modules\graceful-fs\graceful-fs.js:78:16
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:503:3)
```

**Comment by GianlucaGuarini** [comment]
> but this fails 

We describe clearly in our [es6 example](https://github.com/riot/examples/tree/gh-pages/es6) that using babel you will not be able to use riot shortcuts anymore

> We could add an example how to configure it with es6 @GianlucaGuarini ?

I think that following the instructions it's pretty clear but if you think it's necessary you can make a pull request [here](https://github.com/riot/examples) adding the `karma-babel-setup`  

closing this issue, thank you @StarpTech for verifying the question just following our official instructions!

**Comment by StarpTech** [comment]
@GianlucaGuarini thanks for the info. Now it makes sense for me but you dont think its useful to add this hint in the documentation?
